[package]

name = "acorn"
version = "1.0.0"
authors = [ "Tim Cameron Ryan <tim@technical.io>" ]

[[bin]]

name = "acorn"

[dependencies.lazy_static]

git = "https://github.com/Kimundi/lazy-static.rs.git"